# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:trusty
    steps:
      - checkout
      - run: sudo apt-get install ruby-full
      - run: gem install ceedling
      - run: ceedling test:all

workflows:
  run_test:
    jobs:
      - test
